export const SET_TODO = 'SET_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const GET_BY_ID = 'GET_BY_ID'
export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_DONE = 'UPDATE_DONE'